apiVersion: v1
kind: ConfigMap
metadata:
  name: espresso-web-cm
  labels:
    app: {{ .Values.labels.app }} 
data:
    ProductCatalogUrl: "http://espresso-shop-product-catalog-svc:8091"
    ReviewsUrl: "http://espresso-shop-reviews-svc:8092"