apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }} 
  # namespace: s7ivan , I am not creating this namespace becaise helm will create one forme 
  labels:
    app: {{ .Values.labels.app }}

type: Opaque
data:
  password: {{ .Values.secret.key }}